### ISSUE TITLE
How to test with rx.Single

### ISSUE THREAD

**Issue by thaussma** [novoda/rxpresso#11] opened 2015-11-26 12:39 UTC
Hi,
how can I use RxPresso if I use rx.Single instead of rx.Observable?

```
public interface DataRepository {
    Single<User> getUser(String id);
    Single<Articles> getArticles();
}
```

**Comment by Dorvaryn** [comment] 2015-11-26 17:12
The mocking of Single is not yet implemented. It should not be too
difficult to implement. We could use the same backing logic and use
toSingle.
It will be something I'll look into for the next version.

On Thu, 26 Nov 2015, 04:39 thaussma <notifications@github.com> wrote:

> Hi,
> how can I use RxPresso if I use rx.Single instead of rx.Observable?
>
> public interface DataRepository {
>     Single<User> getUser(String id);
>     Single<Articles> getArticles();
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/novoda/rxpresso/issues/11>.
>

-- 
Disclaimer: The information in this e-mail and any attachments is the 
property of Novoda Ltd and is confidential and may be legally privileged. 
This e-mail is intended solely for the person or organisation to which it 
is addressed. Any disclosure, copying or other use of the information by 
any person or organisation who is not the intended recipient is strictly 
prohibited and may be unlawful. If you have received this e-mail in error, 
please inform the sender immediately and delete/destroy this e-mail and any 
copies of it. Novoda Ltd has taken reasonable precautions to minimise the 
risk of any software viruses which may damage your systems, but we advise 
that you take the necessary steps to ensure that no virus contamination is 
suffered. Novoda Ltd does not accept any liability for any loss or damage 
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered 
Office: C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT 
Registration Number  GB 984 2525 93

**Comment by juankysoriano** [comment] 2022-02-11 01:06
Closing as this repository is no longer under maintenance and it's about to be archived

**Closed by juankysoriano** 2022-02-11 01:06 UTC
